In [2]:
import numpy as np
a=[[2,3],[3,4]]
b=[[2,3],[3,4]]
print(np.array(a)*np.array(b))

[[ 4  9]
 [ 9 16]]


In [12]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(a)
print(a[0:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [14]:

print(a)
print(a.sum(axis=1))
print('Полученная размерность:', a[np.newaxis, :].shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
Полученная размерность: (1, 3, 4)


In [18]:
np.cumsum(a,axis=1)

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42]], dtype=int32)

In [19]:
np.abs(np.linspace(-2,2,5))

array([2., 1., 0., 1., 2.])

In [46]:
a=np.array([1, 2, 2, 3, 3, 1 ])

In [59]:
z=np.diff(a)

In [67]:
np.where(np.diff(a)!=0,a,0)

ValueError: operands could not be broadcast together with shapes (5,) (6,) () 

In [68]:
z

array([ 1,  0,  1,  0, -2])

In [52]:
n

In [65]:
from itertools import groupby 
def encode(a):
    return zip(*((key, len(tuple(group))) for key, group in groupby(a)))

 
l = [1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3]
 
print(tuple(encode(l)))

((1, 2, 3, 1, 5, 2, 3), (1, 2, 2, 2, 2, 1, 2))


In [77]:
import numpy as np

def encode(a):
    s = 0
    x=[]
    c=[]
    n=a[0]
    for i in a:       
        if n!=i:
            x.append(n)
            c.append(s)
            s=0
            n=i
        s+=1
    result = np.array(x),np.array(c)
    return result

In [78]:
z=[1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3]

In [79]:
encode(np.array(z))

(array([1, 2, 3, 1, 5, 2]), array([1, 2, 2, 2, 2, 1]))

In [80]:
l = [1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3]

In [85]:
z=np.where(np.diff(l)==0)
z

(array([ 1,  3,  5,  7, 10], dtype=int64),)

In [90]:
np.delete(l,z)

array([1, 2, 3, 1, 5, 2, 3])

In [91]:
np.insert(z,2)

TypeError: insert() missing 1 required positional argument: 'values'

In [96]:
 a = np.array([[1, 1], [2, 2], [3, 3]])
a
 


array([[1, 1],
       [2, 2],
       [3, 3]])

In [97]:
 np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

In [98]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])